### ISSUE TITLE
How do you change the background color?

### ISSUE THREAD

**Issue by elbyrd** [CoatedMoose/CustomViews#1]
The background color of the view is always coming up Black.  How do you change it?

**Comment by ikerexxe** [comment]
You only have to delete the first and the second line of the onDraw method, like this:
    protected void onDraw(Canvas canvas) {
        //canvas.drawColor(Color.BLACK);
        //canvas.drawBitmap(mBitmap, 0, 0, mPaint);
        canvas.drawPath(mPath, mPaint);
    }

**Comment by CoatedMoose** [comment]
This code got copied out of another (non-public) project I was working on. The signature itself should be white on black in the master branch. If it isn't  let me know. I have added a branch (issue-1) that adds a pair of setBackground functions so that you can set the background and foreground colours after initialization.

**Comment by CoatedMoose** [comment]
The copying the code part is relevant because I haven't thoroughly tested this code. It should mostly work, but I did have to change a few things when decoupling the code and didn't fully test everything.

**Comment by ikerexxe** [comment]
Sorry but with the functions that you´ve added to the issue-1 branch I am not able to change the background colour, could you test it? Maybe I´m doing something wrong.

**Comment by CoatedMoose** [comment]
The demo code demonstrates how to change the signature colour. Background can be set using the xml `android:background` property or calling `setBackgroundColor(Color.*)`  on the inflated view.
